apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  selector:
    matchLabels:
      app: mygforce
  template:
    metadata:
      labels:
        app: mygforce
    spec:
      containers:
      - name: gforce-app
        image: claudeeke/maven-web-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: NodePort
  selector:
    app: mygforce
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31000
